name: amap_map_fluttify
description: An `Amap` Map Component, Powered By `Fluttify` Compiler, A Dart Bindings Generator For Native SDK.
version: 1.3.0-pre.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_map_fluttify
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_core_fluttify: ^0.10.0-pre.3
  amap_location_fluttify:
    git:
      url: git@github.com:yohom/amap_location_fluttify.git
  amap_search_fluttify: ^0.12.0-pre.1
  url_launcher: ^5.4.2
  foundation_fluttify: ^0.9.0-pre.10
  core_location_fluttify: ^0.3.0-pre.1

#dependency_overrides:
#  foundation_fluttify:
#    path: /Users/yohom/Github/Me/All/fluttify/fluttify_infra/foundation_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_map_fluttify
        pluginClass: AmapMapFluttifyPlugin
      ios:
        pluginClass: AmapMapFluttifyPlugin